categories:
- media
icon_url: https://media.sys.truenas.net/apps/lifer/icons/icon.png
screenshots:
- https://media.sys.truenas.net/apps/lifer/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/lifer/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/lifer/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/lifer/screenshots/screenshot4.png
tags:
- photos
- wildlife
- birding
- life-list
- archive
