// ESLint for every workspace. Formatting is Prettier's job (eslint-config-prettier turns off the
// rules that would fight it); this config is about correctness.
import js from "@eslint/js";
import prettier from "eslint-config-prettier";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import i18next from "eslint-plugin-i18next";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.venv/**",
      "archive/**",
      "packages/data-pipeline/python/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/.stryker-tmp/**",
      "reports/**",
      "docs/.docusaurus/**",
      "apps/desktop/src-tauri/**",
      "packages/data-pipeline/data/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: { globals: { ...globals.node } },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      // `cond && doThing()` is used deliberately as a one-line conditional call.
      "@typescript-eslint/no-unused-expressions": ["error", { allowShortCircuit: true, allowTernary: true }],
    },
  },
  // TypeScript already reports undefined names, with type information ESLint lacks.
  { files: ["**/*.{ts,tsx}"], rules: { "no-undef": "off" } },
  {
    files: ["apps/web/**/*.{ts,tsx}", "apps/desktop/src/**/*.js"],
    languageOptions: { globals: { ...globals.browser } },
  },
  {
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks, "react-refresh": reactRefresh },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // The React Compiler rules (new in eslint-plugin-react-hooks 7) and the dependency check are
      // errors: the web app is clean, so a new violation fails CI instead of piling up as warnings.
      "react-hooks/set-state-in-effect": "error",
      "react-hooks/refs": "error",
      "react-hooks/purity": "error",
      "react-hooks/immutability": "error",
      "react-hooks/preserve-manual-memoization": "error",
      "react-hooks/exhaustive-deps": "error",
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
    },
  },
  // Every user-visible string in the web app is meant to go through src/locales/en.json (see
  // docs/docs/contributing/translating.md). Lifer is English-only for now and only part of the web
  // app has been moved to en.json, so this rule is off until that's finished (see the roadmap's
  // "More languages" item). Turn it back on to "error" then: it flags hard-coded strings in JSX
  // text, string props and literals inside JSX expressions.
  {
    files: ["apps/web/src/**/*.tsx"],
    ignores: ["**/*.test.tsx"],
    plugins: { i18next },
    rules: {
      "i18next/no-literal-string": [
        "off",
        {
          mode: "jsx-only",
          "jsx-components": { exclude: ["Trans"] },
          "jsx-attributes": {
            exclude: [
              "className",
              "[a-zA-Z]+ClassName",
              "style",
              "type",
              "key",
              "id",
              "width",
              "height",
              "to",
              "href",
              "src",
              "name",
              "role",
              "rel",
              "target",
              "htmlFor",
              "autoComplete",
              "inputMode",
              "accept",
              "mode",
              "variant",
              "size",
              "tone",
              "kind",
              "icon",
              "align",
              "side",
              "placement",
              "as",
              "data-[a-z-]+",
              "aria-(hidden|controls|labelledby|describedby|current|haspopup|live|expanded|pressed|selected|checked|modal|orientation|sort|busy|atomic|relevant|autocomplete|activedescendant|owns|invalid|disabled|level|setsize|posinset|valuenow|valuemin|valuemax)",
              "dataKey",
              "nameKey",
              "stroke",
              "fill",
              "layout",
              "anchor",
              "i18nKey",
              "ns",
              "testId",
              "storageKey",
              "group",
              "format",
              "sizes",
              "loading",
              "decoding",
              "fetchPriority",
              "crossOrigin",
              "referrerPolicy",
              "method",
              "enterKeyHint",
              "spellCheck",
              "dir",
              "lang",
              "pattern",
              "step",
              "min",
              "max",
              "form",
              "download",
              "color",
              "position",
              "direction",
              "orientation",
              "interval",
              "scale",
              "domain",
              "unit",
              "textAnchor",
              "dominantBaseline",
              "cursor",
              "tick",
              "axisLine",
              "tickLine",
              "strokeDasharray",
              "curve",
              "path",
              "query",
              "param",
              "kindFilter",
            ],
          },
          words: {
            // Strings with no letter at all (punctuation, symbols, numbers) never need translating.
            exclude: ["[^\\p{L}]*", "[A-Z_-]+"],
          },
          callees: {
            exclude: [
              "i18n(ext)?",
              "t",
              "i18n\\.t",
              "require",
              "addEventListener",
              "removeEventListener",
              "postMessage",
              "getElementById",
              "querySelector(All)?",
              "includes",
              "indexOf",
              "endsWith",
              "startsWith",
              "navigate",
              "api\\.[a-z]+",
              "fetch",
              "[a-zA-Z]+\\.(get|set|has|delete|append)",
              "classNames|clsx|cn|buttonClass[A-Za-z]*",
              "console\\.[a-z]+",
              "new URL|URL",
              "URLSearchParams",
              "matchMedia",
              "localStorage\\.[a-zA-Z]+",
              "sessionStorage\\.[a-zA-Z]+",
              "setSearchParams",
              "encodeURIComponent",
              "formatDate",
              "toLocaleDateString|toLocaleString",
              "useNavigate|useParams|useSearchParams",
              "track|log",
              "docUrl|docsUrl|docLink",
              "invoke",
            ],
          },
          "object-properties": {
            exclude: [
              "[A-Z_-]+",
              "className",
              "to",
              "href",
              "kind",
              "type",
              "key",
              "id",
              "value",
              "variant",
              "tone",
              "icon",
              "dataKey",
              "position",
              "textAnchor",
              "fill",
              "stroke",
              "color",
              "fontSize",
              "fontWeight",
              "cursor",
              "display",
              "width",
              "height",
            ],
          },
        },
      ],
    },
  },
  // Server code logs through packages/core/src/lib/log.ts (pino). CLI scripts print to the console.
  {
    files: ["apps/api/src/**/*.ts", "packages/core/src/**/*.ts"],
    ignores: ["apps/api/src/admin/**", "**/*.test.ts"],
    rules: { "no-console": "error" },
  },
  prettier,
);
