// eBird's own published sensitive-species list (support.ebird.org/en/support/solutions/articles/48000803210).
// Regenerated from eBird's live "Species treated as Sensitive Globally" + "Regionally Sensitive Species"
// sections. Needs periodic manual refresh if eBird revises its own list — re-fetch the page, re-run the
// parse (see this file's git history for the one-off parser used to build this), regenerate.
//
// A PREVIOUS version of this file flattened every region/season-restricted entry into "sensitive
// everywhere, always" for simplicity. Confirmed live as a real bug: Common Goldeneye is only actually
// sensitive in England (Apr 01-Jul 31, a small rare breeding population there) — its huge winter range
// across all of Canada and Scandinavia was never restricted at all, but the flattened version blurred
// every real hotspot cluster worldwide for it. Now: a species with a regional scope only gets the
// coarse 20x20km treatment when both its region AND season (if any) actually match.
export interface SensitiveSeason {
  startMonth: number;
  startDay: number;
  endMonth: number;
  endDay: number;
}

export interface SensitiveRegionScope {
  // Free-text eBird region label, e.g. "Ontario-CA", "Florida-US", "England-GB" (subnational, suffixed
  // with the country's ISO2 code) or a plain country name like "Mexico" (no suffix) — matched against a
  // province/country name + its own country's ISO2 by sensitiveRegionMatches() below.
  region: string;
  season: SensitiveSeason | null;
}

export type SensitiveScope = { global: true } | { global: false; regions: SensitiveRegionScope[] };

// A sensitive species' hotspot cluster collapses to this fixed diagonal (a 20km x 20km square),
// matching eBird's own obscuring resolution — shared here so both the writer
// (compute-provinces-bulk.ts) and any reader that needs to know "was this specific cluster
// blurred for privacy" (e.g. species/routes.ts, surfacing a note in the UI) check against the
// exact same constant rather than two independently-computed copies.
export const SENSITIVE_CLUSTER_DIAGONAL_KM = 20 * Math.SQRT2;

export const EBIRD_SENSITIVE_SPECIES: Map<string, SensitiveScope> = new Map([
  ["Acridotheres cinereus", { global: true }],
  ["Acridotheres melanopterus", { global: true }],
  ["Aethopyga eximia", { global: true }],
  ["Alophoixus bres", { global: true }],
  ["Alophoixus tephrogenys", { global: true }],
  ["Amandava formosa", { global: true }],
  ["Anodorhynchus glaucus", { global: true }],
  ["Aprosmictus jonquillaceus", { global: true }],
  ["Ara ambiguus", { global: true }],
  ["Aratinga solstitialis", { global: true }],
  ["Ardeotis nigriceps", { global: true }],
  ["Batrachostomus harterti", { global: true }],
  ["Campylopterus phainopeplus", { global: true }],
  ["Centrocercus minimus", { global: true }],
  ["Chloropsis media", { global: true }],
  ["Chloropsis sonnerati", { global: true }],
  ["Chloropsis venusta", { global: true }],
  ["Cissa jefferyi", { global: true }],
  ["Cissa thalassina", { global: true }],
  ["Cochoa azurea", { global: true }],
  ["Cochoa beccarii", { global: true }],
  ["Columba argentina", { global: true }],
  ["Columbina cyanopis", { global: true }],
  ["Copsychus barbouri", { global: true }],
  ["Copsychus malabaricus", { global: true }],
  ["Copsychus nigricauda", { global: true }],
  ["Copsychus omissus", { global: true }],
  ["Copsychus stricklandii", { global: true }],
  ["Corvus hawaiiensis", { global: true }],
  ["Cyornis banyumas", { global: true }],
  ["Dendrocitta occipitalis", { global: true }],
  ["Diuca diuca", { global: true }],
  ["Enicurus velatus", { global: true }],
  ["Eriocnemis isabellae", { global: true }],
  ["Eulidia yarrellii", { global: true }],
  ["Eutrichomyias rowleyi", { global: true }],
  ["Falco cherrug", { global: true }],
  ["Falco deiroleucus", { global: true }],
  ["Falco fasciinucha", { global: true }],
  ["Falco rusticolus", { global: true }],
  ["Gallirallus owstoni", { global: true }],
  ["Garrulax bicolor", { global: true }],
  ["Garrulax palliatus", { global: true }],
  ["Garrulax rufifrons", { global: true }],
  ["Geokichla dohertyi", { global: true }],
  ["Geokichla dumasi", { global: true }],
  ["Geokichla interpres", { global: true }],
  ["Geokichla joiceyi", { global: true }],
  ["Geokichla leucolaema", { global: true }],
  ["Geokichla schistacea", { global: true }],
  ["Glaucidium castanopterum", { global: true }],
  ["Goura cristata", { global: true }],
  ["Gracula religiosa", { global: true }],
  ["Gracula venerata", { global: true }],
  ["Gracupica jalla", { global: true }],
  ["Gubernatrix cristata", { global: true }],
  ["Halcyon cyanoventris", { global: true }],
  ["Heleia javanica", { global: true }],
  ["Heteromirafra ruddi", { global: true }],
  ["Hydrornis guajanus", { global: true }],
  ["Hydrornis gurneyi", { global: true }],
  ["Hypsipetes platenae", { global: true }],
  ["Ianthocincla bieti", { global: true }],
  ["Ianthocincla konkakinhensis", { global: true }],
  ["Ketupa blakistoni", { global: true }],
  ["Ketupa philippensis", { global: true }],
  ["Ketupa zeylonensis", { global: true }],
  ["Laniellus albonotatus", { global: true }],
  ["Laniellus langbianis", { global: true }],
  ["Leiothrix argentauris", { global: true }],
  ["Leucopsar rothschildi", { global: true }],
  ["Liocichla omeiensis", { global: true }],
  ["Lophura edwardsi", { global: true }],
  ["Malacocincla perspicillata", { global: true }],
  ["Mitu mitu", { global: true }],
  ["Myadestes palmeri", { global: true }],
  ["Myiomela diana", { global: true }],
  ["Myiomela sumatrana", { global: true }],
  ["Myophonus glaucinus", { global: true }],
  ["Oriolus isabellae", { global: true }],
  ["Otus alfredi", { global: true }],
  ["Otus angelinae", { global: true }],
  ["Otus jolandae", { global: true }],
  ["Pachycephala nudigula", { global: true }],
  ["Pachycephala orpheus", { global: true }],
  ["Padda fuscata", { global: true }],
  ["Palmeria dolei", { global: true }],
  ["Pampusana hoedtii", { global: true }],
  ["Pedionomus torquatus", { global: true }],
  ["Pica asirensis", { global: true }],
  ["Pithecophaga jefferyi", { global: true }],
  ["Ploceus megarhynchus", { global: true }],
  ["Polyplectron katsumatae", { global: true }],
  ["Polyplectron schleiermacheri", { global: true }],
  ["Pomatorhinus montanus", { global: true }],
  ["Pseudonestor xanthophrys", { global: true }],
  ["Psittacula derbiana", { global: true }],
  ["Pterorhinus berthemyi", { global: true }],
  ["Pterorhinus courtoisi", { global: true }],
  ["Pterorhinus vassali", { global: true }],
  ["Pycnonotus bimaculatus", { global: true }],
  ["Pycnonotus snouckaerti", { global: true }],
  ["Pycnonotus tympanistrigus", { global: true }],
  ["Pycnonotus zeylanicus", { global: true }],
  ["Rhabdotorrhinus waldeni", { global: true }],
  ["Rhinoplax vigil", { global: true }],
  ["Rhipidura euryura", { global: true }],
  ["Rhynchopsitta terrisi", { global: true }],
  ["Sarothrura ayresi", { global: true }],
  ["Scissirostrum dubium", { global: true }],
  ["Spinus cucullatus", { global: true }],
  ["Spinus yarrellii", { global: true }],
  ["Spizocorys fringillaris", { global: true }],
  ["Sporophila crassirostris", { global: true }],
  ["Sporophila maximiliani", { global: true }],
  ["Stachyris thoracica", { global: true }],
  ["Strix butleri", { global: true }],
  ["Strix hadorami", { global: true }],
  ["Strix nebulosa", { global: true }],
  ["Strix occidentalis", { global: true }],
  ["Surnia ulula", { global: true }],
  ["Sypheotides indicus", { global: true }],
  ["Taeniopygia guttata", { global: true }],
  ["Tanygnathus everetti", { global: true }],
  ["Tanygnathus megalorynchos", { global: true }],
  ["Tanygnathus sumatranus", { global: true }],
  ["Todiramphus cinnamominus", { global: true }],
  ["Trichoglossus iris", { global: true }],
  ["Trochalopteron ngoclinhense", { global: true }],
  ["Trochalopteron yersini", { global: true }],
  ["Tympanuchus pallidicinctus", { global: true }],
  ["Zosterops flavus", { global: true }],
  ["Zosterops paruhbesar", { global: true }],
  ["Acrocephalus palustris", { global: false, regions: [{ region: "England-GB", season: { startMonth: 5, startDay: 25, endMonth: 9, endDay: 5 } }] }],
  ["Actinodura sodangorum", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Aegolius acadicus", { global: false, regions: [{ region: "Maryland-US", season: { startMonth: 4, startDay: 1, endMonth: 9, endDay: 30 } }] }],
  ["Aegolius funereus", { global: false, regions: [{ region: "Japan", season: null }, { region: "Lithuania", season: null }, { region: "Minnesota-US", season: null }, { region: "Moscow Oblast-RU", season: null }, { region: "Moscow-RU", season: null }, { region: "New Mexico-US", season: null }, { region: "Switzerland", season: null }, { region: "Wisconsin-US", season: null }, { region: "Wyoming-US", season: { startMonth: 2, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Aethopyga temminckii", { global: false, regions: [{ region: "Thailand", season: null }] }],
  ["Alaemon alaudipes", { global: false, regions: [{ region: "Israel", season: null }, { region: "Palestinian Territory", season: null }] }],
  ["Alauda gulgula", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Alectoris graeca", { global: false, regions: [{ region: "Bayern-DE", season: null }, { region: "Switzerland", season: null }] }],
  ["Alisterus amboinensis", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Alophoixus ochraceus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Alophoixus ruficrissus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Amaurornis phoenicurus", { global: false, regions: [{ region: "South Korea", season: { startMonth: 6, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Amazona auropalliata", { global: false, regions: [{ region: "Belize", season: null }, { region: "Chiapas-MX", season: null }, { region: "Costa Rica", season: null }, { region: "El Salvador", season: null }, { region: "Guatemala", season: null }, { region: "Honduras", season: null }, { region: "Nicaragua", season: null }, { region: "Oaxaca-MX", season: null }] }],
  ["Amazona finschi", { global: false, regions: [{ region: "Chihuahua-MX", season: null }, { region: "Colima-MX", season: null }, { region: "Durango-MX", season: null }, { region: "Guerrero-MX", season: null }, { region: "Jalisco-MX", season: null }, { region: "Michoacán-MX", season: null }, { region: "Nayarit-MX", season: null }, { region: "Oaxaca-MX", season: null }, { region: "Sinaloa-MX", season: null }, { region: "Sonora-MX", season: null }] }],
  ["Amazona oratrix", { global: false, regions: [{ region: "Atlántida-HN", season: null }, { region: "Belize", season: null }, { region: "Campeche-MX", season: null }, { region: "Chiapas-MX", season: null }, { region: "Colima-MX", season: null }, { region: "Cortés-HN", season: null }, { region: "Guerrero-MX", season: null }, { region: "Hidalgo-MX", season: null }, { region: "Izabal-GT", season: null }, { region: "Jalisco-MX", season: null }, { region: "Michoacán-MX", season: null }, { region: "Nayarit-MX", season: null }, { region: "Nuevo León-MX", season: null }, { region: "Oaxaca-MX", season: null }, { region: "Puebla-MX", season: null }, { region: "San Luis Potosí-MX", season: null }, { region: "Tabasco-MX", season: null }, { region: "Tamaulipas-MX", season: null }, { region: "Veracruz-MX", season: null }] }],
  ["Amazona vinacea", { global: false, regions: [{ region: "Argentina", season: null }] }],
  ["Amazona viridigenalis", { global: false, regions: [{ region: "Mexico", season: null }] }],
  ["Amazona vittata", { global: false, regions: [{ region: "Puerto Rico", season: null }] }],
  ["Amazona xantholora", { global: false, regions: [{ region: "Honduras", season: null }, { region: "Mexico", season: null }] }],
  ["Anas luzonica", { global: false, regions: [{ region: "Philippines", season: null }] }],
  ["Anthochaera phrygia", { global: false, regions: [{ region: "Australia", season: { startMonth: 8, startDay: 1, endMonth: 12, endDay: 31 } }] }],
  ["Antigone antigone", { global: false, regions: [{ region: "Chhattisgarh-IN", season: null }] }],
  ["Aquila adalberti", { global: false, regions: [{ region: "Portugal", season: null }] }],
  ["Aquila chrysaetos", { global: false, regions: [{ region: "Bosnia and Herzegovina", season: null }, { region: "Croatia", season: null }, { region: "Israel", season: null }, { region: "Japan", season: null }, { region: "Kosovo", season: null }, { region: "Malopolskie-PL", season: null }, { region: "Montenegro", season: null }, { region: "Moravskoslezský kraj-CZ", season: null }, { region: "North Macedonia", season: null }, { region: "Olomoucký kraj-CZ", season: null }, { region: "Palestinian Territory", season: null }, { region: "Podkarpackie-PL", season: null }, { region: "Pomorskie-PL", season: null }, { region: "Scotland-GB", season: null }, { region: "Serbia", season: null }, { region: "Slaskie-PL", season: null }, { region: "Slovenia", season: null }, { region: "Maine-US", season: { startMonth: 4, startDay: 10, endMonth: 9, endDay: 25 } }, { region: "New York-US", season: { startMonth: 4, startDay: 15, endMonth: 9, endDay: 15 } }, { region: "Italy", season: { startMonth: 3, startDay: 1, endMonth: 8, endDay: 15 } }] }],
  ["Aquila fasciata", { global: false, regions: [{ region: "Israel", season: null }, { region: "Italy", season: null }, { region: "Palestinian Territory", season: null }] }],
  ["Aquila heliaca", { global: false, regions: [{ region: "Bosnia and Herzegovina", season: null }, { region: "Croatia", season: null }, { region: "Georgia", season: null }, { region: "Kosovo", season: null }, { region: "Montenegro", season: null }, { region: "North Macedonia", season: null }, { region: "Serbia", season: null }, { region: "Slovenia", season: null }] }],
  ["Aquila nipalensis", { global: false, regions: [{ region: "Aksaray-TR", season: { startMonth: 3, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Ankara-TR", season: { startMonth: 3, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Konya-TR", season: { startMonth: 3, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kırşehir-TR", season: { startMonth: 3, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Ara glaucogularis", { global: false, regions: [{ region: "Bolivia", season: null }] }],
  ["Ara macao", { global: false, regions: [{ region: "Alta Verapaz-GT", season: null }, { region: "Belize", season: null }, { region: "Chiapas-MX", season: null }, { region: "Honduras", season: null }, { region: "Nicaragua", season: null }, { region: "Petén-GT", season: null }, { region: "Veracruz-MX", season: null }] }],
  ["Ara militaris", { global: false, regions: [{ region: "Mexico", season: null }] }],
  ["Ara rubrogenys", { global: false, regions: [{ region: "Bolivia", season: null }] }],
  ["Asio flammeus", { global: false, regions: [{ region: "Lithuania", season: null }, { region: "New York-US", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 15 } }, { region: "Pennsylvania-US", season: { startMonth: 4, startDay: 20, endMonth: 6, endDay: 30 } }, { region: "Taiwan", season: { startMonth: 1, startDay: 1, endMonth: 3, endDay: 31 } }, { region: "Maryland-US", season: { startMonth: 5, startDay: 1, endMonth: 9, endDay: 30 } }, { region: "Taiwan", season: { startMonth: 10, startDay: 1, endMonth: 12, endDay: 31 } }, { region: "Maryland-US", season: { startMonth: 4, startDay: 1, endMonth: 9, endDay: 30 } }] }],
  ["Asio otus", { global: false, regions: [{ region: "Georgia", season: null }, { region: "Höfuðborgarsvæði-IS", season: null }, { region: "Suðurland-IS", season: null }, { region: "Switzerland", season: null }, { region: "United Kingdom", season: null }, { region: "United States", season: null }, { region: "Vesturland-IS", season: null }, { region: "British Columbia-CA", season: { startMonth: 1, startDay: 1, endMonth: 4, endDay: 30 } }, { region: "Taiwan", season: { startMonth: 1, startDay: 1, endMonth: 3, endDay: 31 } }, { region: "British Columbia-CA", season: { startMonth: 10, startDay: 1, endMonth: 12, endDay: 31 } }, { region: "Taiwan", season: { startMonth: 10, startDay: 1, endMonth: 12, endDay: 31 } }, { region: "Maryland-US", season: { startMonth: 4, startDay: 1, endMonth: 9, endDay: 30 } }, { region: "Wisconsin-US", season: { startMonth: 1, startDay: 1, endMonth: 4, endDay: 15 } }, { region: "New York-US", season: { startMonth: 3, startDay: 1, endMonth: 8, endDay: 15 } }, { region: "Wisconsin-US", season: { startMonth: 11, startDay: 1, endMonth: 12, endDay: 31 } }] }],
  ["Astur atricapillus", { global: false, regions: [{ region: "Maryland-US", season: { startMonth: 4, startDay: 1, endMonth: 8, endDay: 31 } }, { region: "Wisconsin-US", season: { startMonth: 3, startDay: 1, endMonth: 8, endDay: 1 } }, { region: "Pennsylvania-US", season: { startMonth: 3, startDay: 1, endMonth: 8, endDay: 31 } }, { region: "Ontario-CA", season: { startMonth: 3, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "New York-US", season: { startMonth: 3, startDay: 15, endMonth: 8, endDay: 15 } }] }],
  ["Astur gentilis", { global: false, regions: [{ region: "Japan", season: null }, { region: "United Kingdom", season: { startMonth: 2, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Athene cunicularia", { global: false, regions: [{ region: "Alberta-CA", season: null }, { region: "British Columbia-CA", season: null }, { region: "Manitoba-CA", season: null }, { region: "Saskatchewan-CA", season: null }, { region: "Minnesota-US", season: { startMonth: 4, startDay: 15, endMonth: 8, endDay: 31 } }] }],
  ["Athene noctua", { global: false, regions: [{ region: "Czech Republic", season: null }, { region: "Lithuania", season: null }, { region: "Poland", season: null }, { region: "Switzerland", season: null }, { region: "South Korea", season: { startMonth: 2, startDay: 1, endMonth: 9, endDay: 30 } }] }],
  ["Aythya baeri", { global: false, regions: [{ region: "South Korea", season: null }] }],
  ["Aythya marila", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Botaurus eurhythmus", { global: false, regions: [{ region: "South Korea", season: { startMonth: 6, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Botaurus sinensis", { global: false, regions: [{ region: "South Korea", season: { startMonth: 6, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Bubo bengalensis", { global: false, regions: [{ region: "India", season: null }] }],
  ["Bubo bubo", { global: false, regions: [{ region: "Bosnia and Herzegovina", season: null }, { region: "Croatia", season: null }, { region: "Georgia", season: null }, { region: "Germany", season: null }, { region: "Italy", season: null }, { region: "Japan", season: null }, { region: "Kosovo", season: null }, { region: "Lithuania", season: null }, { region: "Mongolia", season: null }, { region: "Montenegro", season: null }, { region: "North Macedonia", season: null }, { region: "Poland", season: null }, { region: "Serbia", season: null }, { region: "Slovenia", season: null }, { region: "Switzerland", season: null }, { region: "South Korea", season: { startMonth: 2, startDay: 1, endMonth: 9, endDay: 30 } }] }],
  ["Bubo scandiacus", { global: false, regions: [{ region: "Iceland", season: null }, { region: "Lithuania", season: null }] }],
  ["Bucephala clangula", { global: false, regions: [{ region: "England-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Buceros bicornis", { global: false, regions: [{ region: "Goa-IN", season: null }, { region: "Karnataka-IN", season: null }, { region: "Kerala-IN", season: null }, { region: "Maharashtra-IN", season: null }, { region: "Tamil Nadu-IN", season: null }] }],
  ["Burhinus oedicnemus", { global: false, regions: [{ region: "England-GB", season: null }, { region: "Baden-Württemberg-DE", season: { startMonth: 3, startDay: 1, endMonth: 9, endDay: 30 } }] }],
  ["Butastur indicus", { global: false, regions: [{ region: "Japan", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Cacatua alba", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Cacatua citrinocristata", { global: false, regions: [{ region: "Nusa Tenggara-ID", season: null }] }],
  ["Cacatua galerita", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Cacatua goffiniana", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Cacatua haematuropygia", { global: false, regions: [{ region: "Philippines", season: null }] }],
  ["Cacatua moluccensis", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Cacatua sulphurea", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Singapore", season: null }, { region: "Timor-Leste", season: null }] }],
  ["Calidris maritima", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Calidris pygmaea", { global: false, regions: [{ region: "Russia", season: null }] }],
  ["Calidris temminckii", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Canachites canadensis", { global: false, regions: [{ region: "New York-US", season: null }, { region: "Vermont-US", season: null }] }],
  ["Caprimulgus aegyptius", { global: false, regions: [{ region: "Israel", season: null }, { region: "Palestinian Territory", season: null }] }],
  ["Caprimulgus europaeus", { global: false, regions: [{ region: "Switzerland", season: null }] }],
  ["Caprimulgus nubicus", { global: false, regions: [{ region: "Israel", season: null }, { region: "Palestinian Territory", season: null }] }],
  ["Carpodacus erythrinus", { global: false, regions: [{ region: "Italy", season: { startMonth: 5, startDay: 15, endMonth: 8, endDay: 15 } }] }],
  ["Centrocercus urophasianus", { global: false, regions: [{ region: "Canada", season: null }, { region: "United States", season: { startMonth: 2, startDay: 1, endMonth: 5, endDay: 31 } }] }],
  ["Centronyx henslowii", { global: false, regions: [{ region: "Ontario-CA", season: { startMonth: 5, startDay: 15, endMonth: 8, endDay: 15 } }] }],
  ["Centropus nigrorufus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Charadrius melodus", { global: false, regions: [{ region: "Wisconsin-US", season: null }] }],
  ["Charmosynopsis toxopei", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Chlamydotis macqueenii", { global: false, regions: [{ region: "Gujarat-IN", season: null }, { region: "Israel", season: null }, { region: "Mongolia", season: null }, { region: "Pakistan", season: null }, { region: "Palestinian Territory", season: null }, { region: "Rajasthan-IN", season: null }] }],
  ["Chloropsis aurifrons", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Chloropsis cochinchinensis", { global: false, regions: [{ region: "Jawa-ID", season: null }] }],
  ["Chloropsis cyanopogon", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Chloropsis hardwickii", { global: false, regions: [{ region: "Malaysia", season: null }, { region: "Vietnam", season: null }] }],
  ["Chloropsis kinabaluensis", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Chloropsis moluccensis", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Malaysia", season: null }] }],
  ["Ciconia nigra", { global: false, regions: [{ region: "Italy", season: { startMonth: 4, startDay: 1, endMonth: 8, endDay: 15 } }, { region: "Germany", season: { startMonth: 3, startDay: 1, endMonth: 8, endDay: 15 } }] }],
  ["Circus cyaneus", { global: false, regions: [{ region: "Isle of Man", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "United Kingdom", season: { startMonth: 2, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Circus pygargus", { global: false, regions: [{ region: "Italy", season: null }, { region: "Sweden", season: null }, { region: "England-GB", season: { startMonth: 4, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Circus spilonotus", { global: false, regions: [{ region: "Japan", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Cissa chinensis", { global: false, regions: [{ region: "China", season: null }, { region: "Indonesia", season: null }, { region: "Malaysia", season: null }, { region: "Vietnam", season: null }] }],
  ["Cissa hypoleuca", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Cisticola juncidis", { global: false, regions: [{ region: "England-GB", season: null }] }],
  ["Cistothorus stellaris", { global: false, regions: [{ region: "Pennsylvania-US", season: { startMonth: 6, startDay: 1, endMonth: 8, endDay: 20 } }] }],
  ["Clanga pomarina", { global: false, regions: [{ region: "Germany", season: { startMonth: 3, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Coccyzus americanus", { global: false, regions: [{ region: "Idaho-US", season: null }] }],
  ["Copsychus pyrropygus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Copsychus saularis", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Malaysia", season: null }] }],
  ["Coracias garrulus", { global: false, regions: [{ region: "Mazowieckie-PL", season: { startMonth: 5, startDay: 1, endMonth: 9, endDay: 1 } }] }],
  ["Cracticus cassicus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Crex crex", { global: false, regions: [{ region: "Switzerland", season: null }, { region: "United Kingdom", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Curruca hortensis", { global: false, regions: [{ region: "Italy", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Curruca leucomelaena", { global: false, regions: [{ region: "Israel", season: null }, { region: "Palestinian Territory", season: null }] }],
  ["Curruca nisoria", { global: false, regions: [{ region: "Italy", season: { startMonth: 4, startDay: 10, endMonth: 7, endDay: 31 } }] }],
  ["Curruca undata", { global: false, regions: [{ region: "United Kingdom", season: null }] }],
  ["Cyanopsitta spixii", { global: false, regions: [{ region: "Brazil", season: null }] }],
  ["Cyclopsitta diophthalma", { global: false, regions: [{ region: "Australia", season: null }] }],
  ["Cygnus cygnus", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Dendrocopos leucotos", { global: false, regions: [{ region: "Sweden", season: null }, { region: "Switzerland", season: null }] }],
  ["Dryobates minor", { global: false, regions: [{ region: "United Kingdom", season: null }] }],
  ["Dryocopus martius", { global: false, regions: [{ region: "Japan", season: { startMonth: 4, startDay: 1, endMonth: 6, endDay: 30 } }] }],
  ["Emberiza aureola", { global: false, regions: [{ region: "China", season: null }, { region: "India", season: null }, { region: "Japan", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Emberiza cirlus", { global: false, regions: [{ region: "United Kingdom", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Epimachus fastosus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Erythrura prasina", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Eudromias morinellus", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Falco biarmicus", { global: false, regions: [{ region: "Albania", season: null }, { region: "Algeria", season: null }, { region: "Andorra", season: null }, { region: "Armenia", season: null }, { region: "Austria", season: null }, { region: "Azerbaijan", season: null }, { region: "Bulgaria", season: null }, { region: "Croatia", season: null }, { region: "Egypt", season: null }, { region: "France", season: null }, { region: "Georgia", season: null }, { region: "Gibraltar", season: null }, { region: "Greece", season: null }, { region: "Hungary", season: null }, { region: "Iraq", season: null }, { region: "Israel", season: null }, { region: "Italy", season: null }, { region: "Jordan", season: null }, { region: "Kosovo", season: null }, { region: "Kuwait", season: null }, { region: "Lebanon", season: null }, { region: "Libya", season: null }, { region: "Monaco", season: null }, { region: "Montenegro", season: null }, { region: "Morocco", season: null }, { region: "North Macedonia", season: null }, { region: "Oman", season: null }, { region: "Palestinian Territory", season: null }, { region: "Portugal", season: null }, { region: "Qatar", season: null }, { region: "Romania", season: null }, { region: "Saudi Arabia", season: null }, { region: "Serbia", season: null }, { region: "Slovenia", season: null }, { region: "Spain", season: null }, { region: "Switzerland", season: null }, { region: "Syria", season: null }, { region: "Tunisia", season: null }, { region: "Türkiye", season: null }, { region: "Western Sahara", season: null }, { region: "Yemen", season: null }] }],
  ["Falco concolor", { global: false, regions: [{ region: "Israel", season: null }, { region: "Palestinian Territory", season: null }] }],
  ["Falco peregrinus", { global: false, regions: [{ region: "Bosnia and Herzegovina", season: null }, { region: "Croatia", season: null }, { region: "Japan", season: null }, { region: "Kosovo", season: null }, { region: "Montenegro", season: null }, { region: "North Macedonia", season: null }, { region: "Serbia", season: null }, { region: "Slovenia", season: null }, { region: "Isle of Man", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "United Kingdom", season: { startMonth: 3, startDay: 7, endMonth: 7, endDay: 31 } }] }],
  ["Ficedula parva", { global: false, regions: [{ region: "Switzerland", season: null }] }],
  ["Forpus cyanopygius", { global: false, regions: [{ region: "Mexico", season: null }] }],
  ["Fringilla montifringilla", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Gallicrex cinerea", { global: false, regions: [{ region: "Taiwan", season: null }, { region: "Thailand", season: null }, { region: "South Korea", season: { startMonth: 6, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Gallinago media", { global: false, regions: [{ region: "Lubelskie-PL", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 1 } }, { region: "Mazowieckie-PL", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 1 } }, { region: "Podlaskie-PL", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 1 } }] }],
  ["Garrulax annamensis", { global: false, regions: [{ region: "Cambodia", season: null }, { region: "Vietnam", season: null }] }],
  ["Garrulax canorus", { global: false, regions: [{ region: "China", season: null }, { region: "Laos", season: null }, { region: "Vietnam", season: null }] }],
  ["Garrulax castanotis", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Garrulax leucolophus", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Garrulax maesi", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Garrulax merulinus", { global: false, regions: [{ region: "China", season: null }, { region: "Myanmar", season: null }, { region: "Thailand", season: null }] }],
  ["Garrulax milleti", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Gavia arctica", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 3, startDay: 15, endMonth: 8, endDay: 31 } }] }],
  ["Gavia immer", { global: false, regions: [{ region: "Wyoming-US", season: { startMonth: 5, startDay: 1, endMonth: 9, endDay: 30 } }] }],
  ["Geokichla citrina", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Vietnam", season: null }] }],
  ["Geokichla erythronota", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Glaucidium brasilianum", { global: false, regions: [{ region: "Arizona-US", season: null }, { region: "California-US", season: null }, { region: "Texas-US", season: null }] }],
  ["Glaucidium capense", { global: false, regions: [{ region: "Eastern Cape-ZA", season: null }] }],
  ["Glaucidium gnoma", { global: false, regions: [{ region: "Wyoming-US", season: { startMonth: 2, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Glaucidium passerinum", { global: false, regions: [{ region: "Lithuania", season: null }, { region: "Poland", season: null }, { region: "Spain", season: null }, { region: "Switzerland", season: null }] }],
  ["Gorsachius goisagi", { global: false, regions: [{ region: "Philippines", season: null }, { region: "South Korea", season: null }, { region: "Japan", season: { startMonth: 4, startDay: 15, endMonth: 8, endDay: 31 } }] }],
  ["Goura scheepmakeri", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Goura sclaterii", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Goura victoria", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Grus americana", { global: false, regions: [{ region: "Georgia-US", season: null }, { region: "Indiana-US", season: null }, { region: "Kentucky-US", season: null }, { region: "Louisiana-US", season: null }, { region: "Nebraska-US", season: null }, { region: "Wisconsin-US", season: null }, { region: "Texas-US", season: { startMonth: 4, startDay: 1, endMonth: 9, endDay: 1 } }] }],
  ["Grus grus", { global: false, regions: [{ region: "United Kingdom", season: null }] }],
  ["Grus japonensis", { global: false, regions: [{ region: "Japan", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Guttera pucherani", { global: false, regions: [{ region: "Pemba North-TZ", season: null }, { region: "Pemba South-TZ", season: null }, { region: "Zanzibar North-TZ", season: null }, { region: "Zanzibar South-TZ", season: null }, { region: "Zanzibar West-TZ", season: null }] }],
  ["Gyps bengalensis", { global: false, regions: [{ region: "Bangladesh", season: null }] }],
  ["Gyps tenuirostris", { global: false, regions: [{ region: "Bangladesh", season: null }] }],
  ["Halcyon coromanda", { global: false, regions: [{ region: "Aichi-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Akita-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Aomori-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Chiba-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Ehime-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Fukui-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Fukuoka-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Fukushima-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Gifu-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Gunma-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Hiroshima-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Hokkaido-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Hyogo-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Ibaraki-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Ishikawa-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Iwate-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Kagawa-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Kanagawa-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Kochi-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Kumamoto-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Kyoto-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Mie-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Miyagi-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Miyazaki-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Nagano-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Nagasaki-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Nara-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Niigata-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Oita-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Okayama-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Osaka-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Saga-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Saitama-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Shiga-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Shimane-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Shizuoka-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Tochigi-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Tokushima-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Tokyo-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Tottori-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Toyama-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Wakayama-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Yamagata-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Yamaguchi-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }, { region: "Yamanashi-JP", season: { startMonth: 4, startDay: 15, endMonth: 7, endDay: 31 } }] }],
  ["Haliaeetus albicilla", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 2, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Japan", season: { startMonth: 3, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Haliaeetus leucoryphus", { global: false, regions: [{ region: "Bangladesh", season: null }] }],
  ["Heliopais personatus", { global: false, regions: [{ region: "Bangladesh", season: null }] }],
  ["Heterophasia desgodinsi", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Himantopus himantopus", { global: false, regions: [{ region: "England-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Hirundo atrocaerulea", { global: false, regions: [{ region: "Eswatini", season: null }, { region: "South Africa", season: null }, { region: "Zimbabwe", season: null }] }],
  ["Hydrocoloeus minutus", { global: false, regions: [{ region: "Norðurland eystra-IS", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Ianthocincla cineracea", { global: false, regions: [{ region: "China", season: null }] }],
  ["Irena puella", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Ketupa flavipes", { global: false, regions: [{ region: "Taiwan", season: null }] }],
  ["Ketupa ketupu", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Lagopus muta", { global: false, regions: [{ region: "Spain", season: null }] }],
  ["Lanius cristatus", { global: false, regions: [{ region: "Aichi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Akita-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Aomori-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Chiba-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Ehime-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Fukui-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Fukuoka-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Fukushima-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Gifu-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Gunma-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Hiroshima-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Hokkaido-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Hyogo-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Ibaraki-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Ishikawa-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Iwate-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kagawa-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kanagawa-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kochi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kumamoto-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kyoto-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Mie-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Miyagi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Miyazaki-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Nagano-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Nagasaki-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Nara-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Niigata-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Oita-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Okayama-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Osaka-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Saga-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Saitama-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Shiga-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Shimane-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Shizuoka-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Tochigi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Tokushima-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Tokyo-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Tottori-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Toyama-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Wakayama-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Yamagata-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Yamaguchi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Yamanashi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Lanius ludovicianus", { global: false, regions: [{ region: "New York-US", season: { startMonth: 4, startDay: 15, endMonth: 8, endDay: 1 } }, { region: "Wisconsin-US", season: { startMonth: 4, startDay: 15, endMonth: 8, endDay: 15 } }, { region: "Pennsylvania-US", season: { startMonth: 5, startDay: 10, endMonth: 7, endDay: 31 } }] }],
  ["Lanius minor", { global: false, regions: [{ region: "Spain", season: null }] }],
  ["Lanius schach", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Lanius tigrinus", { global: false, regions: [{ region: "Japan", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Laterallus jamaicensis", { global: false, regions: [{ region: "Canada", season: null }, { region: "United States", season: null }] }],
  ["Leioptila annectens", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Leistes defilippii", { global: false, regions: [{ region: "Uruguay", season: null }] }],
  ["Leptocoma brasiliana", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Thailand", season: null }] }],
  ["Leucogeranus leucogeranus", { global: false, regions: [{ region: "Mongolia", season: null }] }],
  ["Limnothlypis swainsonii", { global: false, regions: [{ region: "Maryland-US", season: { startMonth: 4, startDay: 10, endMonth: 8, endDay: 20 } }] }],
  ["Locustella luscinioides", { global: false, regions: [{ region: "England-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Wales-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Lonchura ferruginosa", { global: false, regions: [{ region: "Jawa-ID", season: null }, { region: "Nusa Tenggara-ID", season: null }] }],
  ["Loriculus camiguinensis", { global: false, regions: [{ region: "Philippines", season: null }] }],
  ["Loriculus flosculus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Loriculus pusillus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Lorius domicella", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Lorius garrulus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Lorius lory", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Lyrurus tetrix", { global: false, regions: [{ region: "Czech Republic", season: null }, { region: "Germany", season: null }, { region: "Italy", season: null }, { region: "Lithuania", season: null }, { region: "Poland", season: null }, { region: "Slovenia", season: null }, { region: "United Kingdom", season: null }] }],
  ["Melanitta nigra", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Melanocichla lugubris", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Melanocorypha mongolica", { global: false, regions: [{ region: "China", season: null }] }],
  ["Mergus squamatus", { global: false, regions: [{ region: "South Korea", season: null }] }],
  ["Merops apiaster", { global: false, regions: [{ region: "Germany", season: null }, { region: "England-GB", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Scotland-GB", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Micrathene whitneyi", { global: false, regions: [{ region: "California-US", season: null }] }],
  ["Microhierax caerulescens", { global: false, regions: [{ region: "Thailand", season: null }] }],
  ["Mirafra javanica", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Vietnam", season: null }] }],
  ["Monticola saxatilis", { global: false, regions: [{ region: "Bayern-DE", season: null }] }],
  ["Myadestes unicolor", { global: false, regions: [{ region: "Mexico", season: null }] }],
  ["Neohierax insignis", { global: false, regions: [{ region: "Thailand", season: null }] }],
  ["Neophema chrysogaster", { global: false, regions: [{ region: "Australia", season: null }] }],
  ["Neophron percnopterus", { global: false, regions: [{ region: "Italy", season: null }] }],
  ["Ninox japonica", { global: false, regions: [{ region: "Aichi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Akita-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Aomori-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Chiba-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Ehime-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Fukui-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Fukuoka-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Fukushima-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Gifu-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Gunma-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Hiroshima-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Hokkaido-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Hyogo-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Ibaraki-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Ishikawa-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Iwate-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kagawa-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kanagawa-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kochi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kumamoto-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Kyoto-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Mie-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Miyagi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Miyazaki-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Nagano-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Nagasaki-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Nara-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Niigata-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Oita-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Okayama-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Osaka-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Saga-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Saitama-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Shiga-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Shimane-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Shizuoka-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Tochigi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Tokushima-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Tokyo-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Tottori-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Toyama-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Wakayama-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Yamagata-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Yamaguchi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }, { region: "Yamanashi-JP", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Nisaetus nipalensis", { global: false, regions: [{ region: "Japan", season: null }] }],
  ["Numenius arquata", { global: false, regions: [{ region: "Austurland-IS", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Oriolus cruentus", { global: false, regions: [{ region: "Jawa-ID", season: null }] }],
  ["Otis tarda", { global: false, regions: [{ region: "Italy", season: null }, { region: "Mongolia", season: null }, { region: "Morocco", season: null }, { region: "England-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Otus lempiji", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Otus scops", { global: false, regions: [{ region: "Germany", season: null }, { region: "Poland", season: null }, { region: "Switzerland", season: null }] }],
  ["Otus semitorques", { global: false, regions: [{ region: "South Korea", season: { startMonth: 2, startDay: 1, endMonth: 9, endDay: 30 } }] }],
  ["Otus sunia", { global: false, regions: [{ region: "South Korea", season: { startMonth: 2, startDay: 1, endMonth: 9, endDay: 30 } }] }],
  ["Padda oryzivora", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Paludipasser locustella", { global: false, regions: [{ region: "Zimbabwe", season: null }] }],
  ["Passerina ciris", { global: false, regions: [{ region: "Florida-US", season: { startMonth: 1, startDay: 1, endMonth: 4, endDay: 15 } }, { region: "Florida-US", season: { startMonth: 10, startDay: 1, endMonth: 12, endDay: 31 } }] }],
  ["Passerina rositae", { global: false, regions: [{ region: "Mexico", season: null }] }],
  ["Pelecanus crispus", { global: false, regions: [{ region: "Mongolia", season: null }] }],
  ["Perdix perdix", { global: false, regions: [{ region: "Switzerland", season: null }] }],
  ["Pernis apivorus", { global: false, regions: [{ region: "United Kingdom", season: { startMonth: 5, startDay: 1, endMonth: 8, endDay: 20 } }] }],
  ["Pernis ptilorhynchus", { global: false, regions: [{ region: "Japan", season: { startMonth: 5, startDay: 1, endMonth: 8, endDay: 31 } }, { region: "Japan", season: null }] }],
  ["Pezoporus occidentalis", { global: false, regions: [{ region: "Australia", season: null }] }],
  ["Phalaropus fulicarius", { global: false, regions: [{ region: "Iceland", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Phalaropus lobatus", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Phasianus colchicus", { global: false, regions: [{ region: "Mongolia", season: null }] }],
  ["Phodilus badius", { global: false, regions: [{ region: "China", season: null }, { region: "Indonesia", season: null }] }],
  ["Picoides tridactylus", { global: false, regions: [{ region: "Japan", season: null }] }],
  ["Pitohui cerviniventris", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Pitohui kirhocephalus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Pitohui uropygialis", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Pitta nympha", { global: false, regions: [{ region: "China", season: null }, { region: "Taiwan", season: { startMonth: 4, startDay: 1, endMonth: 8, endDay: 31 } }, { region: "Japan", season: { startMonth: 5, startDay: 15, endMonth: 7, endDay: 31 } }] }],
  ["Platylophus galericulatus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Ploceus hypoxanthus", { global: false, regions: [{ region: "Cambodia", season: null }, { region: "Indonesia", season: null }, { region: "Vietnam", season: null }] }],
  ["Podiceps auritus", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 3, startDay: 15, endMonth: 7, endDay: 31 } }] }],
  ["Podiceps nigricollis", { global: false, regions: [{ region: "United Kingdom", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Porzana porzana", { global: false, regions: [{ region: "United Kingdom", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Prioniturus flavicans", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Prioniturus luconensis", { global: false, regions: [{ region: "Philippines", season: null }] }],
  ["Prioniturus mada", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Prioniturus platurus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Prioniturus verticalis", { global: false, regions: [{ region: "Philippines", season: null }] }],
  ["Prionochilus thoracicus", { global: false, regions: [{ region: "Thailand", season: null }] }],
  ["Probosciger aterrimus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Psittacara strenuus", { global: false, regions: [{ region: "Mexico", season: null }] }],
  ["Psittacula alexandri", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Psittacula eupatria", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Psittacula finschii", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Psittacula roseata", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Psittrichas fulgidus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Pterorhinus chinensis", { global: false, regions: [{ region: "Cambodia", season: null }, { region: "China", season: null }, { region: "Hong Kong", season: null }, { region: "Laos", season: null }, { region: "Macau", season: null }, { region: "Myanmar", season: null }, { region: "Thailand", season: null }, { region: "Vietnam", season: null }] }],
  ["Pterorhinus mitratus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Pterorhinus treacheri", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Pycnonotus aurigaster", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Pycnonotus jocosus", { global: false, regions: [{ region: "Thailand", season: null }, { region: "Vietnam", season: null }] }],
  ["Pyrrhocorax pyrrhocorax", { global: false, regions: [{ region: "Isle of Man", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Rallus elegans", { global: false, regions: [{ region: "Ontario-CA", season: null }, { region: "New York-US", season: { startMonth: 3, startDay: 15, endMonth: 8, endDay: 15 } }, { region: "Illinois-US", season: { startMonth: 5, startDay: 15, endMonth: 8, endDay: 1 } }, { region: "Wisconsin-US", season: { startMonth: 5, startDay: 15, endMonth: 8, endDay: 1 } }, { region: "Pennsylvania-US", season: { startMonth: 5, startDay: 15, endMonth: 8, endDay: 20 } }] }],
  ["Rhynchopsitta pachyrhyncha", { global: false, regions: [{ region: "Mexico", season: null }] }],
  ["Rubigula dispar", { global: false, regions: [{ region: "Jawa-ID", season: null }, { region: "Nusa Tenggara-ID", season: null }, { region: "Sumatera-ID", season: null }] }],
  ["Rynchops albicollis", { global: false, regions: [{ region: "India", season: { startMonth: 2, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Sarothrura boehmi", { global: false, regions: [{ region: "South Africa", season: null }, { region: "Zimbabwe", season: null }] }],
  ["Setophaga kirtlandii", { global: false, regions: [{ region: "Wisconsin-US", season: null }, { region: "Quebec-CA", season: { startMonth: 4, startDay: 20, endMonth: 9, endDay: 10 } }, { region: "Ontario-CA", season: { startMonth: 5, startDay: 20, endMonth: 8, endDay: 15 } }] }],
  ["Spilornis cheela", { global: false, regions: [{ region: "Japan", season: null }] }],
  ["Spinus xanthogastrus", { global: false, regions: [{ region: "Venezuela", season: null }] }],
  ["Spizaetus isidori", { global: false, regions: [{ region: "Colombia", season: null }] }],
  ["Sporophila angolensis", { global: false, regions: [{ region: "Venezuela", season: null }] }],
  ["Sporophila cinnamomea", { global: false, regions: [{ region: "Uruguay", season: null }] }],
  ["Sporophila palustris", { global: false, regions: [{ region: "Uruguay", season: null }] }],
  ["Sporophila schistacea", { global: false, regions: [{ region: "Venezuela", season: null }] }],
  ["Stercorarius longicaudus", { global: false, regions: [{ region: "Norðurland eystra-IS", season: { startMonth: 5, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Sterna acuticauda", { global: false, regions: [{ region: "India", season: { startMonth: 2, startDay: 1, endMonth: 6, endDay: 30 } }] }],
  ["Strix leptogrammica", { global: false, regions: [{ region: "Taiwan", season: null }] }],
  ["Strix nivicolum", { global: false, regions: [{ region: "Taiwan", season: null }, { region: "South Korea", season: { startMonth: 2, startDay: 1, endMonth: 9, endDay: 30 } }] }],
  ["Strix seloputo", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Strix uralensis", { global: false, regions: [{ region: "Lithuania", season: null }] }],
  ["Synoicus adansonii", { global: false, regions: [{ region: "Zimbabwe", season: null }] }],
  ["Synoicus chinensis", { global: false, regions: [{ region: "Taiwan", season: null }] }],
  ["Taenioptynx brodiei", { global: false, regions: [{ region: "Taiwan", season: null }] }],
  ["Tanygnathus gramineus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Tanygnathus lucionensis", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Philippines", season: null }] }],
  ["Tauraco fischeri", { global: false, regions: [{ region: "Zanzibar North-TZ", season: null }, { region: "Zanzibar South-TZ", season: null }, { region: "Zanzibar West-TZ", season: null }] }],
  ["Terpsiphone atrocaudata", { global: false, regions: [{ region: "Japan", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Tetrao urogallus", { global: false, regions: [{ region: "Bosnia and Herzegovina", season: null }, { region: "Croatia", season: null }, { region: "Czech Republic", season: null }, { region: "Germany", season: null }, { region: "Italy", season: null }, { region: "Kosovo", season: null }, { region: "Lithuania", season: null }, { region: "Montenegro", season: null }, { region: "North Macedonia", season: null }, { region: "Poland", season: null }, { region: "Serbia", season: null }, { region: "Slovenia", season: null }, { region: "Spain", season: null }, { region: "Switzerland", season: null }, { region: "United Kingdom", season: null }] }],
  ["Tetraogallus altaicus", { global: false, regions: [{ region: "Mongolia", season: null }] }],
  ["Tetrastes bonasia", { global: false, regions: [{ region: "Bosnia and Herzegovina", season: null }, { region: "Croatia", season: null }, { region: "Kosovo", season: null }, { region: "Montenegro", season: null }, { region: "North Macedonia", season: null }, { region: "Serbia", season: null }, { region: "Slovenia", season: null }, { region: "Switzerland", season: null }] }],
  ["Tetrax tetrax", { global: false, regions: [{ region: "Italy", season: null }] }],
  ["Trichoglossus borneus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Trichoglossus capistratus", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Timor-Leste", season: null }] }],
  ["Trichoglossus forsteni", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Timor-Leste", season: null }] }],
  ["Trichoglossus haematodus", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Timor-Leste", season: null }] }],
  ["Trichoglossus histrio", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Trichoglossus johnstoniae", { global: false, regions: [{ region: "Philippines", season: null }] }],
  ["Trichoglossus reticulatus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Trichoglossus rosenbergii", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Papua-ID", season: null }] }],
  ["Trichoglossus rubritorquis", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Timor-Leste", season: null }] }],
  ["Trichoglossus semilarvatus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Trichoglossus squamatus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Trichoglossus weberi", { global: false, regions: [{ region: "Indonesia", season: null }, { region: "Timor-Leste", season: null }] }],
  ["Tringa glareola", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Tringa nebularia", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Tringa ochropus", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 4, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Trochalopteron milnei", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Turdinus macrodactylus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Turdus iliacus", { global: false, regions: [{ region: "Scotland-GB", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Turdus pilaris", { global: false, regions: [{ region: "Norðurland eystra-IS", season: { startMonth: 4, startDay: 1, endMonth: 8, endDay: 31 } }, { region: "Scotland-GB", season: { startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 } }] }],
  ["Turnix sylvaticus", { global: false, regions: [{ region: "Algeria", season: null }, { region: "Gibraltar", season: null }, { region: "Italy", season: null }, { region: "Libya", season: null }, { region: "Morocco", season: null }, { region: "Portugal", season: null }, { region: "Spain", season: null }, { region: "Tunisia", season: null }] }],
  ["Tympanuchus cupido", { global: false, regions: [{ region: "Illinois-US", season: null }] }],
  ["Tympanuchus phasianellus", { global: false, regions: [{ region: "British Columbia-CA", season: null }, { region: "Wisconsin-US", season: null }, { region: "Washington-US", season: { startMonth: 2, startDay: 1, endMonth: 5, endDay: 31 } }] }],
  ["Tyto alba", { global: false, regions: [{ region: "Georgia", season: null }] }],
  ["Tyto capensis", { global: false, regions: [{ region: "Eswatini", season: null }, { region: "South Africa", season: null }, { region: "Zimbabwe", season: null }] }],
  ["Tyto furcata", { global: false, regions: [{ region: "Canada", season: null }, { region: "Maryland-US", season: null }, { region: "New York-US", season: null }, { region: "Pennsylvania-US", season: null }, { region: "Wisconsin-US", season: null }] }],
  ["Tyto javanica", { global: false, regions: [{ region: "China", season: null }, { region: "Indonesia", season: null }] }],
  ["Tyto longimembris", { global: false, regions: [{ region: "Taiwan", season: null }] }],
  ["Urocissa erythroryncha", { global: false, regions: [{ region: "Myanmar", season: null }, { region: "Vietnam", season: null }] }],
  ["Vanellus gregarius", { global: false, regions: [{ region: "Gujarat-IN", season: { startMonth: 1, startDay: 1, endMonth: 3, endDay: 31 } }, { region: "Rajasthan-IN", season: { startMonth: 1, startDay: 1, endMonth: 3, endDay: 31 } }, { region: "Gujarat-IN", season: { startMonth: 11, startDay: 1, endMonth: 12, endDay: 31 } }, { region: "Rajasthan-IN", season: { startMonth: 11, startDay: 1, endMonth: 12, endDay: 31 } }] }],
  ["Xanthopsar flavus", { global: false, regions: [{ region: "Argentina", season: null }, { region: "Uruguay", season: null }] }],
  ["Zapornia fusca", { global: false, regions: [{ region: "South Korea", season: { startMonth: 6, startDay: 1, endMonth: 8, endDay: 31 } }] }],
  ["Zoothera andromedae", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Zosterops atricapilla", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Zosterops auriventer", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Zosterops chloris", { global: false, regions: [{ region: "Jawa-ID", season: null }] }],
  ["Zosterops erythropleurus", { global: false, regions: [{ region: "Vietnam", season: null }] }],
  ["Zosterops japonicus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Zosterops melanurus", { global: false, regions: [{ region: "Indonesia", season: null }] }],
  ["Zosterops simplex", { global: false, regions: [{ region: "Indonesia", season: null }] }],
]);

const MONTH_DAYS = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
function dayOfYear(month: number, day: number): number {
  let doy = day;
  for (let m = 0; m < month - 1; m++) doy += MONTH_DAYS[m];
  return doy;
}

// A GBIF row only carries an ISO week number (1-52), not a real month/day — approximated here by the
// week's own midpoint day, which is precise enough for a coarse season window (eBird's own windows are
// month-granularity to begin with, e.g. "Apr 01-Jul 31") without needing the row's real event date.
export function weekInSeason(week: number, season: SensitiveSeason): boolean {
  const doy = (week - 1) * 7 + 4;
  const start = dayOfYear(season.startMonth, season.startDay);
  const end = dayOfYear(season.endMonth, season.endDay);
  return start <= end ? doy >= start && doy <= end : doy >= start || doy <= end;
}

// provinceName/countryName are this row's own region names (e.g. "England", "United Kingdom");
// countryIso2 is that country's own ISO 3166-1 alpha-2 code (e.g. "GB") — all three already resolved by
// compute-provinces-bulk.ts's own per-country/per-province loop, no extra lookup needed here.
export function sensitiveRegionMatches(label: string, provinceName: string, countryName: string, countryIso2: string): boolean {
  const m = label.match(/^(.+)-([A-Z]{2})$/);
  if (m) return m[2] === countryIso2 && m[1].toLowerCase() === provinceName.toLowerCase();
  return label.toLowerCase() === countryName.toLowerCase();
}
