// Auto-generated by build-species-synonym-map.ts — do not hand-edit entries, regenerate
// instead. Maps a "stale" GBIF taxon key (a name our own DB previously carried as a separate
// species row) to the "keep" GBIF key it was merged into, during the duplicate-species cleanup
// (both sides are independently "ACCEPTED" in GBIF's backbone — sometimes under entirely
// different families — so a fresh GBIF pull would recreate these duplicates without this map).
// Consulted by load-seed.ts: a species row whose gbif_key appears here as a stale key is never
// inserted as its own row — region/sea-zone links for it are attached to the keep species
// instead.
export const SPECIES_SYNONYM_GBIF_KEYS: Record<number, number> = {
  // Antennarius nummifer (Latreille, 1804) -> Antennatus nummifer (Cuvier, 1817), aka
  // Spotfin Frogfish. Confirmed via Wikipedia's own "also known as" list for the species
  // (which includes "Ocellated Fringed Fishing Frog," our stale side's stored common name)
  // and WoRMS (valid name Abantennarius nummifer, same lineage) — a genus-placement dispute
  // across sources, not two different animals.
  "5214726": 7193715,
  // Batch found via alias-cross-check (a species' common_name_aliases exactly matching
  // another species' primary common_name — see find-duplicate-species-via-aliases.ts) then
  // verified per-pair against GBIF's match API (same author + same year, epithet is a clear
  // spelling/OCR-style variant, e.g. missing genitive -i, r/l or a/i letter swap) rather than
  // trusted on pattern alone — several superficially similar same-genus pairs were checked
  // and REJECTED as genuinely distinct species with different authors/years (e.g. Decapterus
  // maruadsi/muroadsi, Mesoplodon mirus/marus, Mesoplodon traversii/travers — the last two are
  // Gervais 1850 names that don't appear in Wikipedia's own synonym list for either accepted
  // species, so were left unmerged despite the tempting spelling similarity).
  "10866317": 2432610, // Anthops omatus -> ornatus (Flower-faced Bat)
  "11707072": 2437245, // Funambulus trisiriatus -> tristriatus
  "11704921": 2438061, // Lenomys meyer -> meyeri
  "11746547": 7261628, // Cratogeomys goldman -> goldmani
  "11512834": 7598901, // Marmota kastschenkot -> kastschenkoi
  "11695250": 11415704, // Myosorex meester -> meesteri
  "11554362": 2437376, // Marmota camischatica -> camtschatica
  "11831492": 2438502, // Dinaromys bogdanouvi -> bogdanovi
  "11760069": 2437243, // Funambulus pennant -> pennantii
  "2417608": 9867851, // Chiloscyllium burmensis -> burmense (WoRMS: burmense accepted)
  "11629672": 2437239, // Hyosciurus heinrich -> heinrichi
  "11826210": 2440039, // Dactylopsila tater -> tatei
  "11422103": 2438764, // Gymnuromys robert -> roberti
  "11462591": 2439942, // Marmosops bishop -> bishopi
  "11528165": 2432140, // Micropotamogale lamotte -> lamottei
  "9599264": 10785624, // Montecincla meridionale -> meridionalis
  "11682583": 2438811, // Mus baouleri -> baoulei
  "11748080": 4265002, // Aconaemys porter -> porteri
  "11418560": 2437548, // Aeretes melanoplerus -> melanopterus
  "11732155": 2433213, // Lonchorhina fernandez -> fernandezi
  "11535091": 2437398, // Callosciurus baluenss -> baluensis
  "11485528": 2435428, // Ningaui ride -> ridei
  "11797772": 4829157, // Macrotarsomys peter -> petteri
  "9466990": 10866083, // Heterotilapia buttikoferi -> buettikoferi (WoRMS: buettikoferi accepted)
  "11590468": 2437288, // Myosciurus pumalio -> pumilio
  "11501140": 4267131, // Cercocebus sanjer -> sanjei
  "2437214": 10787086,
  "2437426": 4972388,
  "2437598": 5786585,
  "2438598": 11779588,
  "2439117": 10878900,
  "2439328": 4828288,
  "2439945": 10819052,
  "2440196": 9589697,
  "2474407": 7371683,
  "2479457": 11218284,
  "2479740": 11175891,
  "2479761": 11208079,
  "2479774": 11195313,
  "2479780": 11195638,
  "2480088": 4851323,
  "2480092": 8852268,
  "2481946": 9772663,
  "2482851": 10824822,
  "2484557": 4845538,
  "2485099": 6088359,
  "2486009": 10770461,
  "2486134": 10813063,
  "2486152": 10727772,
  "2486750": 7487058,
  "2486758": 7674356,
  "2486782": 7415399,
  "2486793": 7898820,
  "2487866": 4409010,
  "2489198": 5789231,
  "2489432": 10748340,
  "2489450": 11122406,
  "2490147": 9456848,
  "2490148": 9630233,
  "2490155": 5788647,
  "2490677": 8925718,
  "2492317": 5789252,
  "2492480": 7711044,
  "2492564": 9561126,
  "2492568": 9599826,
  "2493148": 7743683,
  "2493179": 10949001,
  "2493180": 10771439,
  "2493303": 10787016,
  "2493323": 10899349,
  "2493445": 7874410,
  "2493450": 10598340,
  "2493459": 7851227,
  "2494790": 6086429,
  "2494815": 5846070,
  "2494902": 8964726,
  "2495576": 10743178,
  "2498320": 7373023,
  "4263031": 5786667,
  "4263032": 5786666,
  "4264778": 11529711,
  "4264795": 8725405,
  "4265077": 10728904,
  "4847293": 2481401,
  "5220168": 5787057,
  "5229065": 8150689,
  "5230305": 10678315,
  "5230445": 11065036,
  "5230504": 10673170,
  "5231260": 6090598,
  "5231278": 7561336,
  "5231391": 10316353,
  "5707228": 11375912,
  "5707305": 8091165,
  "5786577": 5219920,
  "5788427": 5229071,
  "5788701": 2486092,
  "5789027": 5231402,
  "5845735": 10789323,
  "5845957": 9478448,
  "5959136": 12232620,
  "6066180": 7763239,
  "6066518": 10095118,
  "6086967": 2493696,
  "6100814": 7366501,
  "6100960": 2482565,
  "6101114": 7592099,
  "6101226": 10810250,
  "7340167": 9000455,
  "7341633": 10680091,
  "7372189": 2489315,
  "7445403": 2493483,
  "7446768": 2493150,
  "7452882": 5231404,
  "7479827": 5788989,
  "7537333": 2493399,
  "7606380": 6066242,
  "7625342": 2493448,
  "7711497": 2493471,
  "7728049": 2496170,
  "7828485": 2484718,
  "7947858": 2493480,
  "7949197": 7340787,
  "8060231": 2493453,
  "8061764": 5788998,
  "8100105": 10598340,
  "8230680": 2493149,
  "8754747": 2480168,
  "8867103": 11172958,
  "9142779": 2485617,
  "9143066": 2480169,
  "9273800": 2489442,
  "9389579": 7341281,
  "9440860": 10747072,
  "9555348": 2490375,
  "9694782": 10731929,
  "9724095": 2480491,
  "9818790": 5789332,
  "9990095": 2492962,
  "10682451": 2481892,
  "10686482": 2474484,
  "10693008": 2493107,
  "10716565": 5229864,
  "10722088": 2492589,
  "10733411": 2478833,
  "10742392": 5230207,
  "10753421": 2474372,
  "10787662": 2486124,
  "10817872": 7261733,
  "10828053": 2474521,
  "10832158": 2479001,
  "10836797": 4265001,
  "10846777": 5788427,
  "10868500": 2493105,
  "10874229": 9574405,
  "10880827": 5230732,
  "10882391": 2484678,
  "10896049": 2486125,
  "10954088": 4262923,
  "11064386": 2490150,
  "11080380": 10977524,
  "11128462": 2479758,
  "11145441": 2473454,
  "11153804": 2479671,
  "11180458": 2479769,
  "11185960": 2479453,
  "11215382": 2479737,
  "11504835": 4265018,
  "11549000": 2439485,
  "11698998": 5219962,
  "11712324": 2432145,
  "11713117": 11067791,
  "11859403": 2439492,
  "11920206": 5219969,
  "11998840": 2432129,
  "12157558": 2432132,
  "12244258": 4264808,
  "12264263": 2437277
};
