// Every GET /api route. A GET or HEAD must not change anything a person would notice, because the
// cross-site write guard lets GETs through (lib/requestGuard.ts), so a page on any site can make a
// signed-in browser send one. apiRoutes.test.ts fails when a GET route isn't listed here, so a new
// one gets a review: add it once its handler, and what that calls, only reads; otherwise make the
// action a POST. The list started from the routes that existed when the test was added, after
// the handler check below.
export const AUDITED_GET_ROUTES: readonly string[] = [
  "/api/auth/setup-status",
  "/api/auth/me",
  "/api/auth/settings",
  "/api/species",
  "/api/species/:id",
  "/api/species/:id/unmatched-raws",
  "/api/species/:id/encounters",
  "/api/species/:id/sequences",
  "/api/species/:id/volume-usage",
  "/api/species/:id/reference-photos",
  "/api/species/:id/reference-photo/display",
  "/api/species/reference-gallery-photo/:photoId/display",
  "/api/species/:id/reference-photo/thumb",
  "/api/species/reference-gallery-photo/:photoId/thumb",
  "/api/species/inat-search",
  "/api/species/other-taxa/bulk/status",
  "/api/species/matching-hardware",
  "/api/species/matching-info",
  "/api/photos/:id/display",
  "/api/photos/:id/medium",
  "/api/photos/:id/thumb",
  "/api/photos/:id/original",
  "/api/photos/:id/original-raw",
  "/api/photos/:id/video",
  "/api/collection",
  "/api/collection/count",
  "/api/collection/stats",
  "/api/gallery/search",
  "/api/gallery",
  "/api/gallery/ids",
  "/api/gallery/has-video",
  "/api/gallery/taxa",
  "/api/gallery/regions-with-photos",
  "/api/originals/:id/download",
  "/api/captures/tags",
  "/api/captures/tags/manage",
  "/api/trash",
  "/api/captures/hidden-count",
  "/api/regions",
  "/api/regions/taxon-presence",
  "/api/regions/:id/photographed-taxa",
  "/api/regions/:id/sea-zones",
  "/api/regions/:id/species",
  "/api/regions/:id/aggregate-species",
  "/api/regions/:id/species/count",
  "/api/regions/boundaries",
  "/api/regions/:regionId/species/:speciesId/hidden-children",
  "/api/regions/hidden-species",
  "/api/regions/:id/hidden-species",
  "/api/regions/:id/checklist-additions",
  "/api/sea-zones",
  "/api/sea-zones/:id/checklist-additions",
  "/api/species/:id/checklist-additions",
  "/api/species/:id/tier",
  "/api/species/:id/split",
  "/api/settings",
  "/api/settings/catalog-update",
  "/api/settings/catalog-update/status",
  "/api/settings/reorganize-originals/status",
  "/api/settings/browse-directory",
  "/api/settings/storage",
  "/api/settings/storage/status",
  "/api/settings/migrate-to-server/status",
  "/api/settings/map/status",
  "/api/settings/embedding-model/status",
  "/api/offline-packs/index",
  "/api/offline-packs/updates-summary",
  "/api/offline-packs/download/status",
  "/api/offline-packs/:packId/delete-preview",
  "/api/offline-packs/:packId/provinces",
  "/api/archive",
  "/api/trips",
  "/api/trips/:id",
  "/api/trips/:id/species",
  "/api/trips/:id/summary",
  "/api/trips/:id/photos",
  "/api/trips/:id/scan/status",
  "/api/trips/:id/scan-preview",
  "/api/trips/:id/import/status",
  "/api/library/folder-status",
  "/api/library/reimport/status",
  "/api/library/reimport/unmatched-preview/:index",
  "/api/library/reimport/unmatched-preview-by-hash/:hash",
  "/api/storage-volumes",
  "/api/stats",
  "/api/stats/export.csv",
  "/api/stats/species-portfolio",
  "/api/stats/archive-health",
  "/api/stats/gear-species-breakdown",
  "/api/stats/year-comparison",
  "/api/stats/photography-dna",
  "/api/albums",
  "/api/albums/:id",
  "/api/albums/:id/species",
  "/api/albums/:id/shares",
  "/api/share/:token",
  "/api/share/:token/photos/:photoId/display",
  "/api/share/:token/photos/:photoId/thumb",
  "/api/api-keys",
  "/api/openapi.json",
  "/api/captures",
  "/api/life-list",
  "/api/life-list/summary",
  "/api/inaturalist/status",
  "/api/inaturalist/callback",
  "/api/inaturalist/server-config",
  "/api/inaturalist/import",
  "/api/inaturalist/pending",
  "/api/inaturalist/completed",
];

// GET routes that do write, and why that's harmless. apiRoutes.test.ts looks for SQL writes in each
// GET handler's own code (not in the helpers it calls) and fails on one that isn't listed here;
// writes made through helpers are listed by hand. Caches and bookkeeping only: nothing here
// changes what the user sees or owns.
export const GET_ROUTES_THAT_WRITE: Readonly<Record<string, string>> = {
  "/api/auth/me":
    "The first time a fresh install's user appears, restores their archived, hidden, seen and target species from the library's own record (once, idempotent).",
  "/api/species/:id": "Records when the species' reference gallery was last fetched (a cache timestamp).",
  "/api/species/:id/reference-photo/display": "Caches the downloaded reference photo's local path.",
  "/api/species/:id/reference-photo/thumb": "Caches the downloaded reference photo's local path.",
  "/api/species/reference-gallery-photo/:photoId/display": "Caches the downloaded gallery photo's local path.",
  "/api/species/reference-gallery-photo/:photoId/thumb": "Caches the downloaded gallery photo's local path.",
  "/api/regions/:id/sea-zones": "Caches the region's computed list of nearby sea zones.",
  "/api/storage-volumes": "Notes when each drive was last seen connected, and its current mount path.",
  "/api/inaturalist/callback":
    "OAuth redirects are GETs. Links the iNaturalist account only for a state value the signed-in user started, so another site can't trigger it.",
};
