-- Video support: a video capture is still just one row in captures/photos/originals, same shape
-- as a photo — only originals.kind and photos.kind widen to include video, no other schema
-- concept changes (species assignment, trips, albums, etc. all already work at the capture
-- level regardless of media kind).
ALTER TABLE originals DROP CONSTRAINT originals_kind_check;
ALTER TABLE originals ADD CONSTRAINT originals_kind_check CHECK (kind IN ('raw', 'jpeg', 'video'));

-- For a video, thumb_path/display_path (unchanged columns) hold poster-frame webp stills,
-- generated by ffmpeg + the same sharp resize pipeline generateDerivatives() already uses for
-- images — same columns, same serving route, no new column needed for that. preview_path is
-- only set when the source video isn't already natively web-playable (H.264/AAC-in-MP4) and
-- needed a transcoded, playback-safe copy generated alongside it; null means the original itself
-- is already web-safe and gets served directly for in-app playback.
ALTER TABLE photos
  ADD COLUMN kind text NOT NULL DEFAULT 'image' CHECK (kind IN ('image', 'video')),
  ADD COLUMN duration_seconds numeric NULL,
  ADD COLUMN preview_path text NULL;
