import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    "intro",
    {
      type: "category",
      label: "Install",
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/install",
        title: "Install",
        description:
          "Run Lifer on your own computer with the desktop app, or on a NAS or server with Docker. Start with the requirements.",
      },
      items: [
        "install/requirements",
        "install/desktop",
        "install/docker",
        "install/upgrading",
        "install/reverse-proxy",
        "install/hardware-acceleration",
        "install/environment-variables",
        "install/backup-restore",
        "install/connect-desktop-to-server",
      ],
    },
    "getting-started",
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "guides/importing",
        "guides/culling-with-other-apps",
        "guides/library-folders",
        "guides/collection-and-checklists",
        "guides/gallery-and-search",
        "guides/trips",
        "guides/albums-and-sharing",
        "guides/ebird-import",
        "guides/inaturalist",
        "guides/offline-packs-and-map",
        "guides/stats",
        "guides/trash",
      ],
    },
    "settings",
    "troubleshooting",
    "faq",
    {
      type: "category",
      label: "Project",
      items: ["support", "roadmap", "credits", "privacy", "security-model", "code-signing"],
    },
    {
      type: "category",
      label: "API",
      items: ["api/overview"],
    },
    {
      type: "category",
      label: "Contributing",
      items: [
        "contributing/development",
        {
          type: "category",
          label: "Design and architecture",
          link: { type: "doc", id: "contributing/architecture" },
          items: [
            "contributing/data-model",
            "contributing/state-and-sync",
            "contributing/imports-and-metadata",
            {
              type: "category",
              label: "Decisions",
              link: { type: "doc", id: "contributing/decisions/index" },
              items: [
                "contributing/decisions/0001-postgresql-everywhere",
                "contributing/decisions/0002-tauri-shell-with-node-sidecar",
                "contributing/decisions/0003-one-api-for-desktop-and-server",
                "contributing/decisions/0004-species-data-shipped-as-release-assets",
                "contributing/decisions/0005-catalog-separate-from-user-data",
                "contributing/decisions/0006-database-primary-files-carry-recovery-copy",
                "contributing/decisions/0007-library-layout-species-folders",
                "contributing/decisions/0008-in-process-onnx-inference",
                "contributing/decisions/0009-compiled-server",
                "contributing/decisions/0010-photo-license-policy",
                "contributing/decisions/0011-typebox-validation-and-generated-openapi",
                "contributing/decisions/0012-no-state-management-library",
              ],
            },
          ],
        },
        "contributing/code-standards",
        "contributing/ai-policy",
        "contributing/review-process",
        "contributing/testing",
        "contributing/database-migrations",
        "contributing/data-pipeline",
        "contributing/rebuilding-data",
        "contributing/desktop-app",
        "contributing/translating",
        "contributing/releasing",
      ],
    },
  ],
};

export default sidebars;
