// One-off: given /tmp/all_pairs_scientific.json (keep + merge scientific names from the
// duplicate-species cleanup), resolves each name to its GBIF usageKey and writes a permanent
// gbif_key synonym map to packages/data-pipeline/src/species-synonyms.ts — consulted by
// load-seed.ts so a future re-import of the GBIF backbone doesn't recreate these same
// duplicate rows (both sides are independently "ACCEPTED" in GBIF's own backbone, sometimes
// under different families entirely, so nothing about a fresh GBIF pull would fix itself).
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { mapWithConcurrency } from "data-pipeline/src/concurrency.js";
import { SPECIES_SYNONYM_GBIF_KEYS as EXISTING } from "data-pipeline/src/species-synonyms.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(__dirname, "..", "..", "..", "..");
const OUTPUT_PATH = path.join(REPO_ROOT, "packages/data-pipeline/src/species-synonyms.ts");

const CONCURRENCY = 6;

interface Pair {
  keep: string;
  merges: string[];
}

async function gbifKeyFor(name: string): Promise<number | null> {
  const res = await fetch(`https://api.gbif.org/v1/species/match?name=${encodeURIComponent(name)}&rank=SPECIES`);
  if (!res.ok) return null;
  const data = (await res.json()) as { usageKey?: number; canonicalName?: string };
  if (!data.usageKey || !data.canonicalName) return null;
  // Guard against a fuzzy/wrong match — require the canonical name to actually match.
  if (data.canonicalName.toLowerCase() !== name.toLowerCase()) return null;
  return data.usageKey;
}

async function main() {
  const pairs: Pair[] = JSON.parse(await (await import("node:fs/promises")).readFile("/tmp/all_pairs_scientific.json", "utf-8"));

  const synonymMap: Record<number, number> = { ...EXISTING };
  const existingCount = Object.keys(EXISTING).length;
  let failed = 0;

  await mapWithConcurrency(pairs, CONCURRENCY, async (pair) => {
    const keepKey = await gbifKeyFor(pair.keep);
    if (!keepKey) {
      console.error(`  no GBIF key for KEEP side: ${pair.keep}`);
      failed++;
      return;
    }
    for (const mergeName of pair.merges) {
      const mergeKey = await gbifKeyFor(mergeName);
      if (!mergeKey) {
        console.error(`  no GBIF key for MERGE side: ${mergeName}`);
        failed++;
        continue;
      }
      synonymMap[mergeKey] = keepKey;
    }
  });

  const newCount = Object.keys(synonymMap).length - existingCount;
  console.log(
    `Resolved ${newCount} new synonym entries (of ${pairs.reduce((n, p) => n + p.merges.length, 0)} attempted, ${failed} failed) — ${Object.keys(synonymMap).length} total in map`,
  );

  const fileContent = `// Auto-generated by build-species-synonym-map.ts — do not hand-edit entries, regenerate
// instead. Maps a "stale" GBIF taxon key (a name our own DB previously carried as a separate
// species row) to the "keep" GBIF key it was merged into, during the duplicate-species cleanup
// (both sides are independently "ACCEPTED" in GBIF's backbone — sometimes under entirely
// different families — so a fresh GBIF pull would recreate these duplicates without this map).
// Consulted by load-seed.ts: a species row whose gbif_key appears here as a stale key is never
// inserted as its own row — region/sea-zone links for it are attached to the keep species
// instead.
export const SPECIES_SYNONYM_GBIF_KEYS: Record<number, number> = ${JSON.stringify(synonymMap, null, 2)};
`;

  writeFileSync(OUTPUT_PATH, fileContent);
  console.log("Wrote packages/data-pipeline/src/species-synonyms.ts");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
